- name: Remove network # noqa: ignore-errors
  become: true
  ignore_errors: true
  block:
    - name: Destroy network
      community.libvirt.virt_net:
        name: "{{ network_name }}"
        command: destroy

    - name: Undefine network
      community.libvirt.virt_net:
        name: "{{ network_name }}"
        command: undefine

    - name: Delete existing bridges (if any)
      community.general.nmcli:
        conn_name: "{{ item }}"
        type: bridge
        state: absent
      loop:
        - "{{ vm_bridge_name }}"
        - "{{ vm_bridge_interface }}_{{ vm_bridge_name }}"
      when: (DELETE_VM_BRIDGE | default(SETUP_VM_BRIDGE | default(true))) | boole

    - name: Delete existing bridges (if any)
      community.general.nmcli:
        conn_name: "{{ vm_bridge_name }}.{{ vm_vlan_tag }}"
        type: vlan
        state: absent
      when: (DELETE_VM_BRIDGE | default(SETUP_VM_BRIDGE | default(true))) | bool and vm_vlan_tag is defined
