---
- name: Verify the certificate variables are set
  assert:
    that:
      - item is defined
      - item is string
      - item | trim != ''
    quiet: true
  loop:
    - "{{ cert_common_name }}"
    - "{{ cert_country }}"
    - "{{ cert_state }}"
    - "{{ cert_locality }}"
    - "{{ cert_organization }}"
    - "{{ cert_organizational_unit }}"

- name: Install python3-cryptography
  package:
    name: python3-cryptography
    state: present
  become: True

- name: Create directory to hold the cert files
  file:
    path: "{{ registry_dir_cert }}"
    owner: "{{ file_owner }}"
    group: "{{ file_group }}"
    mode: 0770
    state: directory
    recurse: yes
  become: true

- name: Generate an OpenSSL private key
  openssl_privatekey:
    path: "{{ registry_dir_cert }}/domain.key"

- name: Generate an OpenSSL CSR
  openssl_csr:
    path: "{{ registry_dir_cert }}/domain.csr"
    privatekey_path: "{{ registry_dir_cert }}/domain.key"
    common_name: "{{ cert_common_name }}"
    country_name: "{{ cert_country }}"
    state_or_province_name: "{{ cert_state }}"
    locality_name: "{{ cert_locality }}"
    organization_name: "{{ cert_organization }}"
    organizational_unit_name: "{{ cert_organizational_unit }}"
    basic_constraints_critical: yes
    create_subject_key_identifier: yes
    basic_constraints: ["CA:TRUE"]

- name: Generate a selfsigned OpenSSL CA Certificate
  openssl_certificate:
    path: "{{ registry_dir_cert }}/domainCA.crt"
    privatekey_path: "{{ registry_dir_cert }}/domain.key"
    csr_path: "{{ registry_dir_cert }}/domain.csr"
    provider: selfsigned

- name: Generate an ownca OpenSSL Certificate
  openssl_certificate:
    path: "{{ registry_dir_cert }}/domain.crt"
    ownca_privatekey_path: "{{ registry_dir_cert }}/domain.key"
    csr_path: "{{ registry_dir_cert }}/domain.csr"
    ownca_path: "{{ registry_dir_cert }}/domainCA.crt"
    ownca_create_authority_key_identifier: yes
    provider: ownca

- name: Set cert in CA trust
  block:
    - name: Copy cert to pki directory
      copy:
        src: "{{ registry_dir_cert }}/domain.crt"
        dest: /etc/pki/ca-trust/source/anchors/domain.crt
        remote_src: yes
        owner: "{{ file_owner }}"
        group: "{{ file_group }}"
        mode: 0660
        force: yes
        backup: yes

    - name: Update the CA trust files
      command: update-ca-trust extract
  become: true

- name: Fetch the domain cert from the registry host
  fetch:
    src: "{{ registry_dir_cert }}/domain.crt"
    dest: "{{ fetched_dest }}/domain.crt"
    flat: yes
  tags:
    - copy_config

- name: Get cert contents
  set_fact:
    mirror_certificate: "{{ lookup('file', fetched_dest + '/domain.crt') }}"

- name: Populate mirror_certificate in bastion
  set_fact:
    mirror_certificate: "{{ mirror_certificate }}"
  delegate_to: bastion
  delegate_facts: true
